### ISSUE TITLE
Both 1.4.5 and 1.4.6 trigger root detection

### ISSUE THREAD

**Issue by diedbug2002** [ys1231/MoveCertificate#11]
- Device: Samsung S9+
 - OS version: 14
 - env: kernelsu

1.4.4 all good

**Comment by ys1231** [comment]
Try downloading 1.4.6 again

**Comment by ys1231** [comment]
Can you describe in detail what you mean by triggering root detection?

**Comment by diedbug2002** [comment]
> Can you describe in detail what you mean by triggering root detection?

同一個app，1.4.4不會偵測到root，1.4.5、1.4.6都偵測到root
所有條件都一樣，只有MoveCertificate版本升級

新版1.4.6已解決

**Comment by ys1231** [comment]
666，👍👍👍，Is it all right now?

**Comment by diedbug2002** [comment]
> 666，👍👍👍，Is it all right now?

新版1.4.6已解決，謝謝
