### ISSUE TITLE
模块不生效

### ISSUE THREAD

**Issue by tongrendx** [ys1231/MoveCertificate#15]
- Device: Xiaomi12Pro
 - OS version: Hyperos1.0.2
 - env: apatch

无日志.
安装后,手机重启进不了系统,应该是触发了apatch了保护,然后自动二次重启,进入系统查看证书,证书安装在用户证书中,未在系统证书.

**Comment by ys1231** [comment]
apatch应该有日志 另外它的模块系统还不完善，是否二次安装过，尝试卸载模块重启后，重新安装。

**Comment by tongrendx** [comment]
重新安装,还是一样的现象.

**Comment by ys1231** [comment]
如果没有日志只能说，跟模块关系不大，都没运行，不会影响系统。或许你可以看看ap的日志，是否启动了模块的脚本。

**Comment by ys1231** [comment]
嗯,我也看到了,事实上在安装的过程中就出错了,开机之后发现文件都不全,可能需要换一种方式去安装,我看看能不能改一下.

**Comment by ys1231** [comment]
较新的Android14 挂载系统证书目录会失败导致系统启动失败,你下载最新的尝试一下.

**Comment by xulonc** [comment]
我的14系统，安装证书后还是 只在 “用户”一栏中出现，“系统”栏 没有。 不过实测，三方证书又是生效的。
我这个是符合预期吗？

**Comment by ys1231** [comment]
符合预期的，想要系统证书出现，可以尝试上一个版本，不过 有些较新的Android14版本会失败。

**Comment by ys1231** [comment]
已修复，关闭。
