### ISSUE TITLE
安装完不是系统证书

### ISSUE THREAD

**Issue by 1i4n** [ys1231/MoveCertificate#19]
安装完之后出现问题不是系统证书，而是用户证书
![6e4856797e1f2547e734b95ec70a7b8](https://github.com/ys1231/MoveCertificate/assets/82950974/1df32cde-b1ad-4a64-b2b7-c022d1f95877)
![431b218e8ff3f45bfd5557114b3b0ca](https://github.com/ys1231/MoveCertificate/assets/82950974/536e16e2-acd9-45b0-b6e9-a1ddb87d8b3c)
![f8a23d08bd3ac87b341030fa4ce1218](https://github.com/ys1231/MoveCertificate/assets/82950974/e2e3972c-dece-4185-96b5-1a2d0133a8b4)
![dbe4fb21193dac9d831b487e3caf849](https://github.com/ys1231/MoveCertificate/assets/82950974/9eb73974-a395-46bb-ad77-acd17da7bf6f)
![c7fa0a4c15abee2c7b0f3a47b4399fd](https://github.com/ys1231/MoveCertificate/assets/82950974/355d94be-5195-4ffe-be69-10988f8824f7)

**Comment by ys1231** [comment]
系统证书看了吗 ？ 两个都放了 。

**Comment by 1i4n** [comment]
系统证书里面没有证书，在用户证书里面有

**Comment by 1i4n** [comment]
佬，可以参照这个项目https://github.com/wanghongenpin/Magisk-ProxyPinCA，这个安装完在系统证书里是正常的

**Comment by ys1231** [comment]
多少有点坑!!!

**Comment by ys1231** [comment]
可以了,人麻了,用了shamiko zygisk 这些就会导致出问题平时都是裸奔,14前几个版本不用管selinux,最新的不设置就挂载失败.
