### ISSUE TITLE
安卓14没有成功

### ISSUE THREAD

**Issue by ksaa4451471** [ys1231/MoveCertificate#21]
- Device: oneplus ace 3v ColorOS 14
 - OS version: 14
 - env: [magisk27]

目前安装看起来一切正常，但是抓包还是证书异常。
然后我在/apex/com.android.conscrypt@340090000的certs目录下面没有找到我预留的证书。大佬有没有思路，或者我该怎么继续排查，谢谢。

**Additional context**
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates status:1
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:1
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed

**Comment by ys1231** [comment]
脚本执行有失败的，status 1 就表示失败，我没有你的环境 你尝试一下 手动执行命令呢？

**Comment by ys1231** [comment]
有不生效的，有启动失败的，第一次遇到执行出错的

**Comment by ys1231** [comment]
在模块目录下 找找看有没有你放的证书

**Comment by ksaa4451471** [comment]
> 脚本执行有失败的，status 1 就表示失败，我没有你的环境 你尝试一下 手动执行命令呢？

可能是根我的手机/system没解锁有关？有时间我吧status=1的跑跑看。

**Comment by ksaa4451471** [comment]
> 在模块目录下 找找看有没有你放的证书

/data/adb/modules/MoveCertificate/certificates/这个路径下是有的

**Comment by ksaa4451471** [comment]
[https://github.com/ys1231/MoveCertificate/blob/iyue/post-fs-data.sh#L31](url)
将证书move 到这里的时候报错才导致之前status：1

/data/misc/user/0/cacerts-added/ 这个路径之前手机里面并没有，可能要判断一下。我创建路径之后发现日志应该是正常了

但是貌似正式并未生效，用户证书倒是成功加进去了
Additional context
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed

**Comment by DanielPPK** [comment]
我遇到了同样的问题，检查是证书没有被push到/apex/com.android.conscrypt/cacerts目录下
我是用手动命令重新mount了一次才可以
mount -o bind /data/adb/modules/MoveCertificate/certificates /apex/com.android.conscrypt/cacerts
stop && start

**Comment by ys1231** [comment]
> [https://github.com/ys1231/MoveCertificate/blob/iyue/post-fs-data.sh#L31](url) 将证书move 到这里的时候报错才导致之前status：1
> 
> /data/misc/user/0/cacerts-added/ 这个路径之前手机里面并没有，可能要判断一下。我创建路径之后发现日志应该是正常了
> 
> 但是貌似正式并未生效，用户证书倒是成功加进去了 Additional context [iyue_MoveCertificate] Keep only one up-to-date log [iyue_MoveCertificate] start move cert ! [iyue_MoveCertificate] current sdk version is 34 [iyue_MoveCertificate] Backup system certificates [iyue_MoveCertificate] Backup user custom certificates [iyue_MoveCertificate] Backup user custom certificates [iyue_MoveCertificate] Backup user custom certificates status:0 [iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/ [iyue_MoveCertificate] fix user permissions status:0 [iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates [iyue_MoveCertificate] fix permissions: 0 [iyue_MoveCertificate] find system conscrypt directory [iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000 [iyue_MoveCertificate] certificates installed

意思是现在的新手机已经没有/data/misc/user/0/cacerts-added/

**Comment by ys1231** [comment]
@DanielPPK 主要没有环境,解决起来还是很快的.我自己这里目前14 很稳定暂时我没法处理.

**Comment by ys1231** [comment]
靠你们了,解决了直接提交来.一起研究.

**Comment by ys1231** [comment]
谁能想到，用户证书目录如果没有安装过证书，这个目录是不存在的！！！

**Comment by bafflingbug** [comment]
> mount -o bind /data/adb/modules/MoveCertificate/certificates /apex/com.android.conscrypt/cacerts
> stop && start

碰见了相同的问题，模块目录下存在用户证书，但是/apex/com.android.conscrypt/cacerts下没有。

**Comment by ys1231** [comment]
你把日志上传一下可能在这之前就报错了

**Comment by bafflingbug** [comment]
> 你把日志上传一下可能在这之前就报错了

# 日志
我自己加了两行
```
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] The directory '/data/local/tmp/cert' is empty.
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] mount /apex/com.android.conscrypt/cacerts status:0
[iyue_MoveCertificate] mount /apex/com.android.conscrypt@340090000/cacerts status:0
[iyue_MoveCertificate] certificates installed
```
# 截图
左侧是`/apex/com.android.conscrypt/cacerts/`, 右侧`/data/adb/modules/MoveCertificate/certificates/`，圈出来的是我自己添加的证书
![2024 05 10_17 35 34](https://github.com/ys1231/MoveCertificate/assets/23716431/2767d49d-c0e0-4f5f-814d-3765d8935e9e)

# 机型与系统
xiaomi 13pro / HyperOS 1.0.6.0

# 模块版本
MoveCertificate-nouser-v1.4.11

**Comment by ys1231** [comment]
看日志是成功的,你命令行 find 一下呢 或者 手动执行一下挂载看看.

**Comment by bafflingbug** [comment]
> 看日志是成功的,你命令行 find 一下呢 或者 手动执行一下挂载看看.

按照楼上提供的命令执行后，符合预期了。
```shell
/data/adb/modules/MoveCertificate/certificates /apex/com.android.conscrypt/cacerts
stop && start
```

**Comment by ys1231** [comment]
不好意思，之前没仔细看，你应该用另一个。这个会导致不信任

**Comment by bafflingbug** [comment]
> 不好意思，之前没仔细看，你应该用另一个。这个会导致不信任

```
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] The directory '/data/local/tmp/cert' is empty.
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed
```
还是会出现相同问题

**Comment by DemonZD** [comment]
遇到了同样的问题，安卓14版本，/system/etc/security/cacerts 有证书，但是/apex/com.android.conscrypt/cacerts下没有 
按照楼上的执行了下面命令，但是我的目录是 /data/adb/modules/movecert/system/etc/security/cacerts
mount -o bind /data/adb/modules/movecert/system/etc/security/cacerts /apex/com.android.conscrypt/cacerts
stop && start
执行过后结果系统证书都没了，只剩下了自己装的抓包用的证书。。。

**Comment by SeeFlowerX** [comment]
readme提到的重启，应该是stop && start，建议完善一下说明
