### ISSUE TITLE
提个建议，可以选择不安装用户证书吗

### ISSUE THREAD

**Issue by MobInfinity** [ys1231/MoveCertificate#22]
可以选择不安装用户证书吗，毕竟可以成功安装系统根证书的话，在安装用户证书是不是有点多此一举。
因为MIUI会在每次开机的时候弹出“网络可能受到监控”吧啦吧啦的，有点烦这个提示。
![Screenshot_2024-04-15-19-39-59-659_com android settings](https://github.com/ys1231/MoveCertificate/assets/79950458/db1911eb-85be-4b8e-b7d2-3729b08e4404)

**Comment by ys1231** [comment]
move_custom_cert
    fix_user_permissions
    把调用位置注释掉 或者 在内部直接返回

**Comment by pdIbq** [comment]
> > ```
> > move_custom_cert
> > fix_user_permissions
> > 把调用位置注释掉 或者 在内部直接返回
> > ```
> 
> 好的，我试试，谢谢

注释掉 或者 在内部直接返回，两种方法都试了。
结果都不能安装系统根证书了。

**Comment by ys1231** [comment]
额 你[下载](https://ys1231.cn:82/modules/MoveCertificate/MoveCertificate-nouserv1.4.10.zip)我改的试试!

**Comment by ys1231** [comment]
你没有抓过chrome吗? 如果不安装证书在用户目录,会出现不信任

**Comment by pdIbq** [comment]
> 你没有抓过chrome吗? 如果不安装证书在用户目录,会出现不信任

确实没有抓过Chrome，刚刚试了一下，发现这个问题了😂
