### ISSUE TITLE
Not working on installation of Zygisk-Assistant

### ISSUE THREAD

**Issue by IamLoot** [ys1231/MoveCertificate#23]
Your module is not working when i use [Zygisk-Assistant](https://github.com/snake-4/Zygisk-Assistant) module. I don't know what problem it has. Please take a look into it.

**Comment by ys1231** [comment]
The certificate directory may have been uninstalled by default, take a look when you have time.

**Comment by ys1231** [comment]
After using Zygisk-Assistant, my phone restarted indefinitely !!!

**Comment by ys1231** [comment]
We will not deal with this issue for the time being. We will deal with it after there is a lot of feedback!

**Comment by paulzzh** [comment]
> We will not deal with this issue for the time being. We will deal with it after there is a lot of feedback!

Same here. Can you reopen this issue?

**Comment by ys1231** [comment]
![Screenshot_2024-11-12-02-01-09-634_me bmax apatch](https://github.com/user-attachments/assets/281e73b1-a46c-47d5-ab19-c21fda805909)
![Screenshot_2024-11-12-02-01-03-421_me bmax apatch](https://github.com/user-attachments/assets/b2bdbe30-5906-4673-acfb-45add17ae65d)
Maybe you should bring the version of the root tool you are using and so on.

**Comment by ys1231** [comment]
> ![Screenshot_2024-11-12-02-01-09-634_me bmax apatch](https://private-user-images.githubusercontent.com/22706022/385020099-281e73b1-a46c-47d5-ab19-c21fda805909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDg1MDQsIm5iZiI6MTczMTM0ODIwNCwicGF0aCI6Ii8yMjcwNjAyMi8zODUwMjAwOTktMjgxZTczYjEtYTQ2Yy00N2Q1LWFiMTktYzIxZmRhODA1OTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE4MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTdkNGYxYTFiYmQwMDY4M2ViMmU0NTZlYzU2MTMxM2JiODMyZWE0ODFlMWMzNjUxN2QxMDE5Y2YxMDNmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VyM6hXWH0Gd46MTqpsKux4QRlyF28lqZC1Jf9CD1s24) ![Screenshot_2024-11-12-02-01-03-421_me bmax apatch](https://private-user-images.githubusercontent.com/22706022/385020130-b2bdbe30-5906-4673-acfb-45add17ae65d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDg1MDQsIm5iZiI6MTczMTM0ODIwNCwicGF0aCI6Ii8yMjcwNjAyMi8zODUwMjAxMzAtYjJiZGJlMzAtNTkwNi00NjczLWFjZmItNDVhZGQxN2FlNjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE4MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMTlhZThjODQ5MDBjYWU2MmYwNjRjMzE3ZjcyYWFiMWEwMDgwY2ZkMjcxOTg1OGI2NWM2OWM1YWQzZGI1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7WsBqE3BWhuCjULTw7TOSMxnf8psgKIJ8NbGKg0LEsA)也许您应该带上您正在使用的 root 工具的版本，依此类推。

I am doing well at present.

**Comment by ys1231** [comment]
It is recommended to bring, system version, root software and module version, and resubmit this information to issue.

**Comment by paulzzh** [comment]
Android 14-QPR2
KernelSU 0.9.5 (11872) (The last version that supports non-GKI devices)
Zygisk-Next 1.2.3
Zygisk-Assistant 2.1.3
MoveCertificate 1.5.2
![190267a4e117e56ef46fb9616b95c8c7_720](https://github.com/user-attachments/assets/b0db9ef8-ce21-4d48-8600-9d761323a03a)
MoveCertificate works fine without Zygisk-Assistant. <img width="325" alt="60b6597e39e936a9f173f2cd6ec8b68b" src="https://github.com/user-attachments/assets/020d2e25-13a7-4e8f-ac73-179329398b57">

After enable Zygisk-Assistant, Chrome still works, but some third-party applications failed. ![image](https://github.com/user-attachments/assets/a84bd099-f3ad-404c-8026-d79215026cef) ![ad2105693190e7d341e017b7716a63ba](https://github.com/user-attachments/assets/e3514d61-51d5-41b7-a339-5b56518dad7e)
