### ISSUE TITLE
证书不生效

### ISSUE THREAD

**Issue by yunxiaoshu** [ys1231/MoveCertificate#24]
查看系统凭据，均已移动过去了，用户凭据也存在，抓包证书仍然显示不信任
环境：ksu
内核：4.19.259

**Comment by ys1231** [comment]
我猜你抓的不是chrome

**Comment by yunxiaoshu** [comment]
> 我猜你抓的不是chrome

抓的是chrome里的baidu，提示证书无效，但是比较玄学的是，我在设置里的证书管理里看见用户侧和系统测都有证书。之后我在ksu里把您的模块关闭后，重启手机，发现系统侧没了证书，用户侧还有。但是我再用抓包工具抓包的时候，成功抓到了https，系统是paranoid，android13，真玄学

**Comment by ys1231** [comment]
你是不是用的nouser那个 那个chrome 是抓不到的
