### ISSUE TITLE
Device root status got detect when I enable the module

### ISSUE THREAD

**Issue by Zhen-Bo** [ys1231/MoveCertificate#25]
- Device: Xiaomi 13
 - OS version: MIUI EU 14.0.31.0.TMCCNXM
 - env: kernelsu 11413
 - install version: 1.4.11

- installed module:
  - Zygisk - LSPosed V1.9.2(7024)
  - Shamiko v1.0.1 (300)
  - Zygisk Next v1.0.3(287-bd5b40a-release)

ESUN Bank APP / line pay will detect device root status after I enabled MoveCertificate.
Is there any way to hide root when I enable the module?

**Comment by ys1231** [comment]
有时间看看,之前在忙.

**Comment by ys1231** [comment]
Is it only when you pay? No login, no prompt.

**Comment by Zhen-Bo** [comment]
I think you need to login to line to use line pay🤔
https://github.com/ys1231/MoveCertificate/assets/30999421/bdee1ec0-b37e-4cfc-a75a-1e58adc3e66d

**Comment by ys1231** [comment]
It seems that root has been detected, and the specific logic needs to be analyzed.

**Comment by ys1231** [comment]
I don't have time to deal with this kind of problem, ignore it for the time being, and analyze it if a large number of them are detected in the future

**Comment by RevealedSoulEven** [comment]
It is
