### ISSUE TITLE
Pixel4 Android13 Chrome does not trust

### ISSUE THREAD

**Issue by you3k** [ys1231/MoveCertificate#27]
The certificate has been installed in the system directory. It can be used by other apps. Only the Google browser cannot. After checking, it is because /system/etc/security/cacerts_google exists in the system. Have you considered adding this directory?

**Comment by ys1231** [comment]
What is the version number of the Chrome browser?I haven't met it.

**Comment by you3k** [comment]
It is a system application and its version is Chrome 101.0.4951.74 ,google/flame/flame:13/TP1A.220624.014

**Comment by ys1231** [comment]
You are trying to upgrade to the latest version.

**Comment by ys1231** [comment]
It has been used normally, close this issues
