### ISSUE TITLE
doesn't work on ONEPLUS Ace 3

### ISSUE THREAD

**Issue by zr4in** [ys1231/MoveCertificate#28]
- Device: [ ONEPLUS Ace 3 ]
- OS version: [ 14, PJE110_14.0.0.810(CN01) ]
- env: [ magisk 27.0(27000) ]
- installed module: [ Zygisk - LSPosed V1.9.2 ]

**Additional context**
I followed “手动安装证书到系统证书目录”
The certificate is still in user's direcotry after reboot.

 `/data/adb/modules/MoveCertificate/install.log` is shown below:
```
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed
```

**Comment by ys1231** [comment]
By default, it is installed in both the system certificate directory and the user certificate directory. You can try to grab the package and make sure.

**Comment by zr4in** [comment]
I tried use polarproxy to provide a socks5 proxy and appproxy as a socks5 client. Still cannot see any decrypted tls traffic. `ls /system/etc/security/cacerts` shows that the certificate is not there.

**Comment by ys1231** [comment]
The certificate you converted manually may be wrong. You can try to use the system's own settings to install the certificate and restart it, or extract '********.0' from another phone after installing it and put it in '/data' /local/tmp/cert' inside

**Comment by zr4in** [comment]
Thanks for your patience. I've actually tried using the system's setting page. The certificate is still in user's directory. The content of install.log:
```
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] The directory '/data/local/tmp/cert' is empty.
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed
```

**Comment by zr4in** [comment]
I'll try to extract the certificate from another phone later.

**Comment by ys1231** [comment]
!!!, both directories will be placed, otherwise chrome will not be able to catch it

**Comment by zr4in** [comment]
OK, I'm trying.

**Comment by zr4in** [comment]
Sorry for the delay. I'm not sure about the "both directories" are which. I manually installed the certificate in system's setting page and extract ‘xxxxxx.0’ from another phone then push it to /data/local/tmp/cert. Nothing changes. install.log:
```
[iyue_MoveCertificate] Keep only one up-to-date log
[iyue_MoveCertificate] start move cert !
[iyue_MoveCertificate] current sdk version is 34
[iyue_MoveCertificate] Backup system certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates
[iyue_MoveCertificate] Backup user custom certificates status:0
[iyue_MoveCertificate] fix user permissions: /data/misc/user/0/cacerts-added/
[iyue_MoveCertificate] fix user permissions status:0
[iyue_MoveCertificate] fix permissions: /data/adb/modules/MoveCertificate/certificates
[iyue_MoveCertificate] fix permissions: 0
[iyue_MoveCertificate] find system conscrypt directory
[iyue_MoveCertificate] find conscrypt directory: /apex/com.android.conscrypt@340090000
[iyue_MoveCertificate] certificates installed
```

**Comment by zr4in** [comment]
> I manually installed the certificate in system's setting page and extract ‘xxxxxx.0’ from another phone then push it to /data/local/tmp/cert.

Is this the correct way to use this module?

**Comment by ys1231** [comment]
In theory, you only need to install the certificate in the system settings.

**Comment by zr4in** [comment]
On the Pixel 6, I installed the certificate through the system settings successfully. Anyway, I finally decided to give up and try a different phone.

**Comment by zr4in** [comment]
update:
Works fine with ONEPLUS 8 Pro running ColorOS13 (IN2020_13.1.0.120(CN01)). Only need to install the certificate via the system settings and reboot. After that, the certificate will be located in both the user's directrory and the system's directory.
