### ISSUE TITLE
KernelSU网页优化

### ISSUE THREAD

**Issue by cocoyamnut** [ys1231/MoveCertificate#34]
证书列表在文件后面的Unknown能否显示正常名字？

**Comment by ys1231** [comment]
可以 我只收集了比较常用的,你是安装什么软件的证书,我加进去.

**Comment by lsdlh** [comment]
> 可以 我只收集了比较常用的,你是安装什么软件的证书,我加进去.

httpcanary reqable proxypin

**Comment by lsdlh** [comment]
![1e6874492dd5ba4636f00a747d4d34b](https://github.com/user-attachments/assets/f66d3fff-4da8-45e2-a1b1-8367e760940c)
页面没看到删除按钮？kernelsu

**Comment by ys1231** [comment]
长按显示删除，正常情况也不需要删除就没直接显示。晚上有空加上去。

**Comment by ys1231** [comment]
你这里有4个 应该还有一个吧

**Comment by TopMaps** [comment]
![Snipaste_2024-11-08_22-43-46](https://github.com/user-attachments/assets/e7f57c31-2da9-449f-ac8d-ee8af347ca08)
已经装了reqable、sunny证书，列表貌似显示异常？
环境：安卓11+Apatch

**Comment by ys1231** [comment]
已经修复了
