### ISSUE TITLE
[WebUI] 无法显示证书列表

### ISSUE THREAD

**Issue by paulzzh** [ys1231/MoveCertificate#35]
- Device: [ Oneplus 7T ]
- OS version: [ 14 ]
- env: [ kernelsu 11872 ]
- installed module: [ Zygisk - LSPosed V1.10.1 , Zygisk Next v1.2.3 ]

**Additional context**
KernelSU Manager v1.0.2 / v0.9.5
toast: `TypeError: Failed to fetch.`
webui debug:
![image](https://github.com/user-attachments/assets/66c88361-1aff-4c8c-a5d7-4f7e94e1be6a)

**Comment by paulzzh** [comment]
CORS preflight
![image](https://github.com/user-attachments/assets/2ecd0e5e-dc8a-4efc-97f7-6085e06b2dc5)
![image](https://github.com/user-attachments/assets/003de835-ab43-4215-8885-29b70a6c80f7)

**Comment by ys1231** [comment]
The server restarted at 2:30. I didn’t expect anyone to be using it so late. It should be normal now.

**Comment by paulzzh** [comment]
still failed.

script.e07801fb.js:1 
POST https://cert.ys1231.cn/query 400 (Bad Request)

payload: {"name":"cert base64","data":""}
response: {"error": "Key: 'Data' Error:Field validation for 'Data' failed on the 'required' tag"}

Two certificates have been installed by placing certs to /data/local/tmp/cert/*
![image](https://github.com/user-attachments/assets/4585ce87-7475-4094-ba5e-c9d71dfa1e8c)

**Comment by ys1231** [comment]
The certificate format you put in /data/local/tmp/cert is wrong.

**Comment by paulzzh** [comment]
![image](https://github.com/user-attachments/assets/b2508b6d-2696-4760-9bd2-9d031e31ebe2)
![image](https://github.com/user-attachments/assets/2165d280-50dd-4b90-a2c2-df22a041ce13)
It's working.

**Comment by ys1231** [comment]
Can I capture the packet? chrome

**Comment by ys1231** [comment]
Or send me the certificate file to see if my service is not compatible with this certificate format.

**Comment by paulzzh** [comment]
> Or send me the certificate file to see if my service is not compatible with this certificate format.

[mitm.zip](https://github.com/user-attachments/files/17713214/mitm.zip)
Both formats can be used on my device, whether it's base64 or binary, but the module does not display certs on webui.

**Comment by paulzzh** [comment]
[mui.kernelsu.org.har.zip](https://github.com/user-attachments/files/17713308/mui.kernelsu.org.har.zip)
Chrome captured data.

**Comment by ys1231** [comment]
I can do it here. Have you installed the latest version of the module and whether the network connection is successful?

**Comment by ys1231** [comment]
![image](https://github.com/user-attachments/assets/0b670092-1a60-4402-80e9-cd1350796b6f)

**Comment by paulzzh** [comment]
> [mui.kernelsu.org.har.zip](https://github.com/user-attachments/files/17713308/mui.kernelsu.org.har.zip) Chrome captured data.

Android 14-QPR2
KernelSU 0.9.5 (11872) (The last version that supports non-GKI devices)
Zygisk-Next 1.2.3

MoveCertificate 1.5.2 (latest)

It's reporting 400 Bad Request.

**Comment by ys1231** [comment]
The data you requested locally is empty, so you can try to use the new version of kernelsu to report an error.

**Comment by paulzzh** [comment]
#22
Comment out the code and do not install the user certificate.
So this part failed and return empty.
getCertName requires passing the certificate path, not a directory.
![image](https://github.com/user-attachments/assets/89bd74f7-9dac-42f5-b213-aa7e6cdd0a12)
https://github.com/ys1231/MoveCertificate/blob/b4bbebdd0d72f8be085705410a32640078270f86/script.js#L187-L206
![image](https://github.com/user-attachments/assets/7014d388-6767-4424-9ea3-88da80322d01)
