### ISSUE TITLE
Andoroid 12 无法抓包

### ISSUE THREAD

**Issue by tiandaozhendehuichouqin** [ys1231/MoveCertificate#37]
- Device: [ 一加 9 ] root
- OS version: [ 12  ]
- env: [ magisk  ]
- installed module: [ Magisk 27 ,LSPosed v1.9.2, shamiko v1.0.1, MoveCertificate v1.5.2]

系统证书和用户证书都好了，但是http和https 还是抓不到，
![微信截图_20241205102057](https://github.com/user-attachments/assets/d132940a-7681-4f71-b87a-9f5489953a23)

我是新手，捣鼓了几天也搞不了
我看了几个文章，感觉不知道是自己哪里配错了
https://mp.weixin.qq.com/s/8JxX_tAQb4YDzu5kyckbtw
https://mp.weixin.qq.com/s/Iu8jrKQ6PkDQ0OUyhAjkNA

**Comment by tiandaozhendehuichouqin** [comment]
![111](https://github.com/user-attachments/assets/27e27cea-07dd-466f-9ef5-4397f82d604c)

**Comment by ys1231** [comment]
1. 即使没有安装任何证书 http也能抓到，很明显你的环境有问题，这不属于本模块解决范畴，可以找其他教程学习处理相信你花点时间学一下可以搞定。

**Comment by tiandaozhendehuichouqin** [comment]
谢谢大哥 ！！！！

**Comment by tiandaozhendehuichouqin** [comment]
已解决

解决方案：
踩坑点
1、建议使用热点测试
2、关闭防火墙
3、https://github.com/ys1231/MoveCertificate/issues/37
4、安装好证书
