### ISSUE TITLE
安卓14支持一下吧

### ISSUE THREAD

**Issue by leosj** [ys1231/MoveCertificate#4]

**Comment by ys1231** [comment]
目前没有Android14的手机，没法测试有说证书无法识别可以尝试：`pm uninstall com.google.android.conscrypt`

**Comment by timmy-gzw** [comment]
我也发现 Android 14 没生效

**Comment by ys1231** [comment]
https://book.hacktricks.xyz/v/cn/mobile-pentesting/android-app-pentesting/install-burp-certificate 这里有两个Android14的安装证书方案，我没有试过 没有14的手机，还在用13！！！

**Comment by ys1231** [comment]
https://github.com/ys1231/MoveCertificate/releases/tag/v1.4.1
顺便帮我测试一下是否可用

**Comment by tpnet** [comment]
> https://github.com/ys1231/MoveCertificate/releases/tag/v1.4.1 顺便帮我测试一下是否可用

@ys1231  哥，测试了魅族21，Android14用不了。

**Comment by UjuiUjuMandan** [comment]
https://github.com/NVISOsecurity/MagiskTrustUserCerts/issues/31

**Comment by ys1231** [comment]
已经测试Android14 可正常识别。
