### ISSUE TITLE
关于证书倒入用户组的问题

### ISSUE THREAD

**Issue by 0clickjacking0** [ys1231/MoveCertificate#5]
你好开发者，我是android9，已经把burp证书倒入到系统证书里了，但抓https还是会存在提示证书不可信

**Comment by ys1231** [comment]
嗯，我有时间测试一下，目前我的环境是Android12 kernelsu 可以正常抓Chrome google.com

**Comment by 0clickjacking0** [comment]
好的我再试试，非常感谢，而且我修改了system:system为root:root好像也是提示证书不可信

**Comment by ys1231** [comment]
![Screenshot_2024-01-06-12-22-41-768_bin mt plus](https://github.com/ys1231/MoveCertificate/assets/22706022/fec9a22a-89d9-429d-8390-0f23ace16dfd)
可以看到系统证书目录已经改为root用户，可以看一下源码脚本里面也是，至于用户证书是system，是系统默认行为，如果修改为root，可以解决你的问题那也是值得高兴的事情。

**Comment by 0clickjacking0** [comment]
谢谢，大概率是证书有效期时间过长导致被浏览器屏蔽了，感谢开发者
