### ISSUE TITLE
pixel2 android11 重启后，证书未生效，证书 权限错误

### ISSUE THREAD

**Issue by YaronWong** [ys1231/MoveCertificate#7]
感谢大佬提供模块
设备 pixel2 android11 ，masgisk 26100
步骤：
1.httpcanary 导出证书后，安装证书 (用户证书)
2.重启
3.安装MoveCertificate模块
4.重启
查看/system/etc/security/cacerts
-????????? ? ?    ?       ?                ? 87bc3517.0
![image](https://github.com/ys1231/MoveCertificate/assets/68764452/1fa9d0e8-dafe-42c2-b854-34ae2af5a6a9)
求教如何解决，感谢~

**Comment by ys1231** [comment]
https://ys1231.cn:82/modules/MoveCertificate/MoveCertificate-v1.4.2.zip 
你试试这个

**Comment by YaronWong** [comment]
感谢解答 
用的模块方案，把证书放到模块zip中可以实现证书安装
：）
