### ISSUE TITLE
小米12 hyperOS无效

### ISSUE THREAD

**Issue by Cheukfung** [ys1231/MoveCertificate#8]
安卓14 2024-02-01安全补丁，安装模块后，用户证书消失，打开系统证书界面会重启，重启后用户证书和系统证书均没有

**Comment by ys1231** [comment]
嗯 ， 我小米还在社区三级，没有hyperOS可以调试测试这些。

**Comment by ys1231** [comment]
可以打开证书目录看一下权限是否正确，以及证书是否存在。

**Comment by Cheukfung** [comment]
system/etc/security/cacerts存在该证书，权限正确，apex目录不存在证书，系统设置没有该证书

**Comment by ys1231** [comment]
确实存在问题,之前是朋友测试的,我自己升级一个Android14测试一下.

**Comment by ys1231** [comment]
<img width="1304" alt="iShot_2024-02-19_01 27 27" src="https://github.com/ys1231/MoveCertificate/assets/22706022/7935953c-1cae-4f72-9bea-89eebbc370b6">

**Comment by ys1231** [comment]
感谢告知,实测有个逻辑错误已修复

**Comment by Cheukfung** [comment]
用了新版的模块依旧不行，降到MIUI14就可以，可能是澎湃系统有什么特别的地方

**Comment by ys1231** [comment]
羡慕，我还没用上hyperos！

**Comment by Cheukfung** [comment]
我的小米12已经有正式版了，你的如果没有正式版的包，试试替换法升级开发版？https://hyperos.fans/

**Comment by Cheukfung** [comment]
另外用了最新的模块，证书无法正常安装，但是会不定时重启，我不得不删掉模块

**Comment by ys1231** [comment]
感谢你的提醒,晚上去社区看了下放出卡刷包了,用上了hyperos,感觉变化不大,最新版已经兼容hyperos.

**Comment by Cheukfung** [comment]
我测试还是不行，设备：小米12，hyperos 1.0.2.0.ULCCNXM，Magisk版本 27001。安装1.4.4版本的模块，system和apex下的目录证书均没有找到证书。

**Comment by ys1231** [comment]
新的逻辑 不会放到 system目录  会放到这个目录  /apex/com.android.conscrypt/cacerts/  我是在kernelsu上面测试的和magisk的执行时机是一致的。我也是12pro 和你的版本一致。

**Comment by Cheukfung** [comment]
那可能是magisk的问题？

**Comment by ys1231** [comment]
![image](https://github.com/ys1231/MoveCertificate/assets/22706022/c8d89df1-8016-49c1-9e85-35e184ab6e35)
![image](https://github.com/ys1231/MoveCertificate/assets/22706022/6f10d8cf-8577-4217-9d22-449db5c57b61)
![image](https://github.com/ys1231/MoveCertificate/assets/22706022/a5d93cf0-8eec-4fc3-8e3c-96728245b284)
![image](https://github.com/ys1231/MoveCertificate/assets/22706022/c807e324-99b8-4a2b-9451-6c83eb7d614f)

我是主力机不能随意切换环境,不过理论上是可以的

**Comment by ys1231** [comment]
![image](https://github.com/ys1231/MoveCertificate/assets/22706022/a021e9ab-ddbe-4388-ac68-e7b0a3d34511)
magisk应该不存在这个问题.你可以试试其他支持Android14的模块。https://github.com/nccgroup/ConscryptTrustUserCerts 或者其他的 之前我用的和这个逻辑一致，后面放弃了。

**Comment by Cheukfung** [comment]
用这个https://github.com/nccgroup/ConscryptTrustUserCerts直接会重启，我放弃了。用ksu算了
