### ISSUE TITLE
miui13系统（安卓12）安装fiddler的cer证书问题

### ISSUE THREAD

**Issue by 365bug** [ys1231/MoveCertificate#9]
miui13系统（安卓12）安装fiddler的cer证书，magisk安装此插件后，重启后浏览器弹框提示“安全警告，该网站的安全证书有问题”，查看证书提示，证书并非来自可信的授权中心，大佬是否可以看下此问题原因，感谢！

**Comment by ys1231** [comment]
我怎么看,我用的pixel3xl 系统是12 是正常使用的,你看一下 `/data/adb/modules/MoveCertificate` 路径下是否有 `certificates`目录 且权限是否正常

**Comment by 365bug** [comment]
certificates目录下有0结尾的证书文件，权限是rw-r--r--（644），是不是权限受限了？现在用的是你提供1.4.2版本插件

**Comment by ys1231** [comment]
目录权限是 755 .0文件权限是644  其它权限会导致系统无法识别 /system/etc/security/cacerts 这个目录检查一下 可以

**Comment by 365bug** [comment]
/system/etc/security/cacerts 中system，etc，security，三个目录都是(rwxr-xr-x)，cacerts目录 （rwxrwxrwt）其中269953fb.0(fiddler证书)权限rw-r--r--（644），9a5ba575.0(burp证书)权限rw-r--r--（644），经过测试发现，burp可以正常捕获https流量，只是fiddler抓包提示非信任证书，fiddler导出安装证书后缀是.cer，burp导出的正式后缀是.der,是否证书格式问题？

**Comment by ys1231** [comment]
证书有效期可能需要检查一下。能用就行应该和格式无关，安装到手机上后 都是统一的格式。

**Comment by 365bug** [comment]
为了排除证书问题，重新生成了证书，fiddler证书确认是在有效期内的。目前用burp进行抓包没问题。

**Comment by 365bug** [comment]
问题终于解决，问题出在新版本的Android拒绝超过两年有效期的证书，下载fiddlercertmaker.exe（下载地址：http://www.fiddler2.com/r/?fiddlercertMaker，确保已关闭Fiddler），下载完后打开fiddlercertmaker，会弹出提示导入证书成功这个对话框
![image](https://github.com/ys1231/MoveCertificate/assets/57247956/df71325b-d421-41e6-9a2a-7d16346b0158)
然后将Fiddler的证书导出到电脑，点击Tools -> Options -> HTTPS -> Actions -> Export Root Certificate to Desktop，启用MoveCertificate14.3插件，重启后，fiddler可正常抓包。

**Comment by ys1231** [comment]
我好像在哪看到过这个问题，Android14 已经实现基于google play去更新系统证书了，不需要超过两年也是正常逻辑了。恭喜，又可以愉快的玩耍了。
